package amalitech.hospital.management.model.lab;

import amalitech.hospital.management.enums.LabOrderStatus;
import amalitech.hospital.management.enums.converter.LabOrderStatusConverter;
import amalitech.hospital.management.model.doctor.Doctor;
import amalitech.hospital.management.model.patient.Appointment;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `lab_orders` table.
 * Each lab order belongs to one appointment and is requested by one doctor.
 */
@Data
@Entity
@Table(name = "lab_orders")
public class LabOrder {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "lab_order_id", updatable = false, nullable = false)
    private String labOrderId;

    /** FK -> appointments */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_laborder_appointment"))
    private Appointment appointment;

    /** FK -> doctors (ordering doctor) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "doctor_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_laborder_doctor"))
    private Doctor doctor;

    @Column(name = "test_name", nullable = false, length = 150)
    private String testName;

    @Convert(converter = LabOrderStatusConverter.class)
    @Column(name = "status", nullable = false, length = 20)
    private LabOrderStatus status = LabOrderStatus.ORDERED;

    @Column(name = "ordered_at", nullable = false)
    private LocalDateTime orderedAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
