package amalitech.hospital.management.model.lab;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `lab_results` table.
 * Each lab result belongs to exactly one lab order.
 */
@Data
@Entity
@Table(name = "lab_results")
public class LabResult {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "lab_result_id", updatable = false, nullable = false)
    private String labResultId;

    /** FK -> lab_orders (unique, one-to-one) */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "lab_order_id", nullable = false, unique = true,
            foreignKey = @ForeignKey(name = "fk_labresult_laborder"))
    private LabOrder labOrder;

    @Column(name = "result_value", length = 100)
    private String resultValue;

    @Column(name = "unit", length = 20)
    private String unit;

    @Column(name = "reference_range", length = 50)
    private String referenceRange;

    @Column(name = "is_abnormal", nullable = false)
    private Boolean isAbnormal = false;

    @Column(name = "completed_at")
    private LocalDateTime completedAt;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
