package amalitech.hospital.management.model.doctor;

import amalitech.hospital.management.enums.ScheduleDay;
import amalitech.hospital.management.enums.converter.ScheduleDayConverter;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Entity model for the `doctor_schedules` table.
 * Every column in the schema is represented as a field below.
 */
@Data
@Entity
@Table(name = "doctor_schedules",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"doctor_id", "day_of_week", "start_time", "end_time"})
        })
public class DoctorSchedule {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "schedule_id", updatable = false, nullable = false)
    private String scheduleId;

    /** FK -> doctors */
    @Column(name = "doctor_id", nullable = false)
    private String doctorId;

    @Convert(converter = ScheduleDayConverter.class)
    @Column(name = "day_of_week", nullable = false, length = 3)
    private ScheduleDay dayOfWeek;

    @Column(name = "start_time", nullable = false)
    private LocalTime startTime;

    /** must be after startTime */
    @Column(name = "end_time", nullable = false)
    private LocalTime endTime;

    @Column(name = "is_available")
    private Boolean isAvailable;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** soft delete marker, null = active */
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
