package amalitech.hospital.management.model.doctor;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;
import java.time.LocalTime;

/**
 * Entity model for the `doctor_schedules` table.
 * Every column in the schema is represented as a field below.
 */
@Data
@Entity
@Table(name = "doctor_schedules",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"doctorId", "dayOfWeek", "startTime", "endTime"})
        })
public class DoctorSchedule {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String scheduleId;

    /** FK -> doctors */
    @Column(nullable = false)
    private String doctorId;

    /** 'Mon'..'Sun' */
    @Column(nullable = false)
    private String dayOfWeek;

    @Column(nullable = false)
    private LocalTime startTime;

    /** must be after startTime */
    @Column(nullable = false)
    private LocalTime endTime;

    private Boolean isAvailable;

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    /** soft delete marker, null = active */
    private LocalDateTime deletedAt;
}
