package amalitech.hospital.management.model.user.logs;

import amalitech.hospital.management.model.user.User;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `audit_log` table.
 * Records user actions performed on specific tables and records.
 */
@Data
@Entity
@Table(name = "audit_log")
public class AuditLog {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "log_id", updatable = false, nullable = false)
    private String logId;

    /** FK -> users (nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id",
            foreignKey = @ForeignKey(name = "fk_auditlog_user"))
    private User user;

    @Column(name = "action", nullable = false, length = 50)
    private String action;

    @Column(name = "table_affected", nullable = false, length = 50)
    private String tableAffected;

    @Column(name = "record_id")
    private String recordId; // UUID of the affected record

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}
