package amalitech.hospital.management.model.user.logs;

import amalitech.hospital.management.model.user.User;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `system_logs` table.
 * Captures system-level events with severity, source, and message.
 */
@Data
@Entity
@Table(name = "system_logs")
public class SystemLog {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "log_id", updatable = false, nullable = false)
    private String logId;

    @Column(name = "log_level", nullable = false, length = 10)
    private String logLevel; // DEBUG, INFO, WARNING, ERROR

    @Column(name = "source", length = 100)
    private String source;

    @Column(name = "message", columnDefinition = "TEXT", nullable = false)
    private String message;

    /** FK -> users (nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id",
            foreignKey = @ForeignKey(name = "fk_systemlog_user"))
    private User user;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}
