package amalitech.hospital.management.model.notification;

import amalitech.hospital.management.model.user.User;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `notifications` table.
 * Each notification may be triggered by a user (actor) and sent to multiple recipients.
 */
@Data
@Entity
@Table(name = "notifications")
public class Notification {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "notification_id", updatable = false, nullable = false)
    private String notificationId;

    @Column(name = "type", nullable = false, length = 100)
    private String type;

    /** FK -> users (actor who triggered the notification, nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actor_user_id",
            foreignKey = @ForeignKey(name = "fk_notification_user"))
    private User actor;

    /** JSONB fields — can be mapped as String or ObjectNode (Jackson) */
    @Column(name = "recipients", columnDefinition = "jsonb", nullable = false)
    private String recipients = "[]"; // default empty array

    @Column(name = "payload", columnDefinition = "jsonb")
    private String payload;

    @Column(name = "channels", columnDefinition = "jsonb")
    private String channels;

    @Column(name = "status", columnDefinition = "jsonb")
    private String status;

    @Column(name = "priority", nullable = false, length = 20)
    private String priority = "normal";
    // values: 'low','normal','high'

    @Column(name = "read_at")
    private LocalDateTime readAt;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
