package amalitech.hospital.management.model.notification;

import amalitech.hospital.management.model.user.User;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;

/**
 * Entity model for the `notifications` table.
 * Each notification may be triggered by a user (actor) and sent to multiple recipients.
 */
@Data
@Entity
@Table(name = "notifications",
        indexes = {
                // Backs NotificationRepository.findByReadAtIsNull/findByReadAtIsNotNull —
                // NotificationService.getNotifications' unread filter.
                @Index(name = "idx_notifications_read_at", columnList = "read_at")
        })
public class Notification {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "notification_id", updatable = false, nullable = false)
    private String notificationId;

    @Column(name = "type", nullable = false, length = 100)
    private String type;

    /** FK -> users (actor who triggered the notification, nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actor_user_id",
            foreignKey = @ForeignKey(name = "fk_notification_user"))
    private User actor;

    /** JSONB fields, mapped as plain {@code String} (a caller-facing shape decided at the
     *  service layer — see {@code NotificationService}), but {@code @JdbcTypeCode(SqlTypes.JSON)}
     *  is required so Hibernate actually binds the parameter as {@code jsonb} rather than
     *  {@code varchar} — without it, Postgres rejects every insert/update with "column is
     *  of type jsonb but expression is of type character varying" (only surfaced once a
     *  real caller — {@code NotificationService} — ran an actual insert; every entity
     *  field here was otherwise unexercised scaffolding until that vertical was built). */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "recipients", columnDefinition = "jsonb", nullable = false)
    private String recipients = "[]"; // default empty array

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "payload", columnDefinition = "jsonb")
    private String payload;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "channels", columnDefinition = "jsonb")
    private String channels;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "status", columnDefinition = "jsonb")
    private String status;

    @Column(name = "priority", nullable = false, length = 20)
    private String priority = "normal";
    // values: 'low','normal','high'

    @Column(name = "read_at")
    private LocalDateTime readAt;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
