package amalitech.hospital.management.model.user;

import amalitech.hospital.management.model.doctor.Doctor;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `users` table.
 * Each user may optionally be linked to a doctor account.
 */
@Data
@Entity
@Table(name = "users",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"username"}),
                @UniqueConstraint(columnNames = {"email"})
        })
public class User {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "user_id", updatable = false, nullable = false)
    private String userId;

    /** FK -> doctors (nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "doctor_id",
            foreignKey = @ForeignKey(name = "fk_user_doctor"))
    private Doctor doctor;

    @Column(name = "username", nullable = false, length = 50, unique = true)
    private String username;

    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    @Column(name = "email", length = 100, unique = true)
    private String email;

    @Column(name = "is_active", nullable = false)
    private Boolean isActive = true;

    /** {@code null} = not verified yet, or no email was ever on file to verify — see
     *  {@code AuthService.login}'s gate and {@code AuthService.verifyEmail}. Set
     *  immediately (not via the link flow) for accounts {@code UserService.createUserByAdmin}
     *  provisions, since receiving the generated password at that address already proves
     *  deliverability. */
    @Column(name = "email_verified_at")
    private LocalDateTime emailVerifiedAt;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
