package amalitech.hospital.management.model.user;

import amalitech.hospital.management.model.user.role.Role;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `user_invites` table — an admin pre-authorizing a role for an
 * email address before that person has ever registered. No {@code User} row exists yet
 * when this is created; {@link InviteService#consumeInviteIfAny} looks one up by email
 * the moment a brand-new account (self-registration or first Google OAuth2 login)
 * actually shows up under that address, and assigns {@link #role} instead of the
 * generic Guest fallback.
 */
@Data
@Entity
@Table(name = "user_invites")
public class UserInvite {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "invite_id", updatable = false, nullable = false)
    private String inviteId;

    @Column(name = "email", nullable = false, length = 100)
    private String email;

    /** The role granted the moment this invite is consumed. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "role_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_invite_role"))
    private Role role;

    /** The admin who created this invite. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "invited_by_user_id",
            foreignKey = @ForeignKey(name = "fk_invite_inviter"))
    private User invitedBy;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    /** {@code null} = not yet consumed. Set the moment a matching new account is created. */
    @Column(name = "accepted_at")
    private LocalDateTime acceptedAt;

    /** {@code null} = still live. Set when an admin cancels the invite before it's used. */
    @Column(name = "revoked_at")
    private LocalDateTime revokedAt;
}
