package amalitech.hospital.management.model.patient;

import amalitech.hospital.management.enums.AppointmentStatus;
import amalitech.hospital.management.enums.converter.AppointmentStatusConverter;
import amalitech.hospital.management.model.doctor.Doctor;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `appointments` table.
 * Each appointment links one patient and one doctor.
 */
@Data
@Entity
@Table(name = "appointments",
        indexes = {
                // Backs AppointmentService.throwIfDoctorDoubleBooked's
                // findByDoctor_DoctorIdAndDeletedAtIsNull — every create/update runs this,
                // and without an index it's a full table scan of every appointment ever
                // booked, for every doctor, on every request.
                @Index(name = "idx_appointments_doctor_id", columnList = "doctor_id"),
                // Backs AppointmentService.getAppointments' status filter and the
                // "?sort=appointmentDate" case both REST and GraphQL listings support.
                @Index(name = "idx_appointments_appointment_date", columnList = "appointment_date")
        })
public class Appointment {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "appointment_id", updatable = false, nullable = false)
    private String appointmentId;

    /** FK -> patients */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_appointment_patient"))
    private Patient patient;

    /** FK -> doctors */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "doctor_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_appointment_doctor"))
    private Doctor doctor;

    @Column(name = "appointment_date", nullable = false)
    private LocalDateTime appointmentDate;

    @Convert(converter = AppointmentStatusConverter.class)
    @Column(name = "status", nullable = false, length = 20)
    private AppointmentStatus status = AppointmentStatus.SCHEDULED;

    @Column(name = "reason", length = 255)
    private String reason;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
