package amalitech.hospital.management.model.patient;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `medical_records` table.
 * Each medical record belongs to exactly one appointment.
 */
@Data
@Entity
@Table(name = "medical_records")
public class MedicalRecord {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "record_id", updatable = false, nullable = false)
    private String recordId;

    /** FK -> appointments (unique, one-to-one) */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id", nullable = false, unique = true,
            foreignKey = @ForeignKey(name = "fk_medicalrecord_appointment"))
    private Appointment appointment;

    @Column(name = "diagnosis", length = 255)
    private String diagnosis;

    @Column(name = "symptoms", columnDefinition = "TEXT")
    private String symptoms;

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
