package amalitech.hospital.management.model.patient;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity model for the `patient_feedback` table.
 * Feedback can be linked to a patient, appointment, and submitted user.
 */
@Data
@Entity
@Table(name = "patient_feedback")
public class PatientFeedback {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "feedback_id", updatable = false, nullable = false)
    private String feedbackId;

    /** FK -> patients */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id",
            foreignKey = @ForeignKey(name = "fk_feedback_patient"))
    private Patient patient;

    /** FK -> appointments (nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id",
            foreignKey = @ForeignKey(name = "fk_feedback_appointment"))
    private Appointment appointment;

    /** FK -> users (to be defined later) */
    @Column(name = "submitted_by")
    private String submittedBy;
    // Once Users entity is defined, replace with @ManyToOne

    @Column(name = "rating", nullable = false)
    private Short rating; // values: 1–5

    @Column(name = "comments", columnDefinition = "TEXT")
    private String comments;

    @Column(name = "date_submitted", nullable = false)
    private LocalDate dateSubmitted;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
