package amalitech.hospital.management.model.patient;

import amalitech.hospital.management.model.user.User;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `patient_notes` table.
 * Each note belongs to a patient, may be tied to an appointment,
 * and is authored by a user (doctor, nurse, admin, etc.).
 */
@Data
@Entity
@Table(name = "patient_notes")
public class PatientNote {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "note_id", updatable = false, nullable = false)
    private String noteId;

    /** FK -> patients */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_note_patient"))
    private Patient patient;

    /** FK -> appointments (nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id",
            foreignKey = @ForeignKey(name = "fk_note_appointment"))
    private Appointment appointment;

    /** FK -> users (author of the note, nullable, ON DELETE SET NULL) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author_user_id",
            foreignKey = @ForeignKey(name = "fk_note_user"))
    private User author;

    @Column(name = "author_role", length = 50)
    private String authorRole;

    @Column(name = "note_text", columnDefinition = "TEXT", nullable = false)
    private String noteText;

    @Column(name = "source", length = 50, nullable = false)
    private String source = "medical_records"; // default

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
