package amalitech.hospital.management.model.patient;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `patient_allergies` table.
 * Each allergy belongs to one patient.
 */
@Data
@Entity
@Table(name = "patient_allergies")
public class PatientAllergy {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "allergy_id", updatable = false, nullable = false)
    private String allergyId;

    /** FK -> patients */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "patient_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_allergy_patient"))
    private Patient patient;

    @Column(name = "allergen", nullable = false, length = 100)
    private String allergen;

    @Column(name = "reaction", length = 255)
    private String reaction;

    @Column(name = "severity", length = 10)
    private String severity; // values: 'mild','moderate','severe'

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
