package amalitech.hospital.management.model.patient;

import amalitech.hospital.management.model.doctor.Doctor;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `referrals` table.
 * Each referral links one appointment, a referring doctor, and a referred-to doctor.
 */
@Data
@Entity
@Table(name = "referrals",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"appointment_id"})
        })
public class Referral {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "referral_id", updatable = false, nullable = false)
    private String referralId;

    /** FK -> appointments */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_referral_appointment"))
    private Appointment appointment;

    /** FK -> doctors (referring doctor) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "referring_doctor_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_referral_referring_doctor"))
    private Doctor referringDoctor;

    /** FK -> doctors (referred-to doctor) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "referred_to_doctor_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_referral_referred_doctor"))
    private Doctor referredToDoctor;

    @Column(name = "reason", length = 255)
    private String reason;

    @Column(name = "status", nullable = false, length = 20)
    private String status = "pending"; // values: 'pending','scheduled','completed'

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
