package amalitech.hospital.management.model.patient;

import amalitech.hospital.management.model.patient.Appointment;
import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity model for the `vital_signs` table.
 * Each vital sign record belongs to one appointment.
 */
@Data
@Entity
@Table(name = "vital_signs")
public class VitalSign {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "vital_id", updatable = false, nullable = false)
    private String vitalId;

    /** FK -> appointments */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_vitals_appointment"))
    private Appointment appointment;

    @Column(name = "blood_pressure_systolic")
    private Short bloodPressureSystolic; // 1–300

    @Column(name = "blood_pressure_diastolic")
    private Short bloodPressureDiastolic; // 1–200

    @Column(name = "heart_rate")
    private Short heartRate; // > 0

    @Column(name = "temperature_celsius", precision = 4, scale = 1)
    private BigDecimal temperatureCelsius;

    @Column(name = "weight_kg", precision = 5, scale = 2)
    private BigDecimal weightKg;

    @Column(name = "height_cm", precision = 5, scale = 2)
    private BigDecimal heightCm;

    @Column(name = "recorded_at", nullable = false)
    private LocalDateTime recordedAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
