package amalitech.hospital.management.model.pharmacy;

import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity model for the `medications` table.
 */
@Data
@Entity
@Table(name = "medications",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"name"})
        })
public class Medication {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "medication_id", updatable = false, nullable = false)
    private String medicationId;

    @Column(name = "name", nullable = false, length = 150)
    private String name;

    @Column(name = "generic_name", length = 150)
    private String genericName;

    @Column(name = "form", length = 50)
    private String form;

    @Column(name = "unit_price", precision = 10, scale = 2)
    private BigDecimal unitPrice; // must be >= 0

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
