package amalitech.hospital.management.model.pharmacy;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity model for the `medical_inventory` table.
 * Each inventory record belongs to one medication.
 */
@Data
@Entity
@Table(name = "medical_inventory")
public class MedicalInventory {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "inventory_id", updatable = false, nullable = false)
    private String inventoryId;

    /** FK -> medications */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medication_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_inventory_medication"))
    private Medication medication;

    @Column(name = "batch_number", length = 50)
    private String batchNumber;

    @Column(name = "expiry_date", nullable = false)
    private LocalDate expiryDate;

    @Column(name = "quantity_in_stock", nullable = false)
    private Integer quantityInStock = 0; // must be >= 0

    @Column(name = "reorder_level", nullable = false)
    private Integer reorderLevel = 10;

    @Column(name = "supplier", length = 100)
    private String supplier;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
