package amalitech.hospital.management.model.pharmacy;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity model for the `prescription_items` table.
 * Each item links a prescription to a medication with dosage and instructions.
 */
@Data
@Entity
@Table(name = "prescription_items")
public class PrescriptionItem {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "item_id", updatable = false, nullable = false)
    private String itemId;

    /** FK -> prescriptions */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "prescription_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_item_prescription"))
    private Prescription prescription;

    /** FK -> medications */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "medication_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_item_medication"))
    private Medication medication;

    @Column(name = "dosage", length = 50)
    private String dosage;

    @Column(name = "quantity", nullable = false)
    private Integer quantity; // must be > 0

    @Column(name = "instructions", length = 255)
    private String instructions;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
