package amalitech.hospital.management.model.pharmacy;

import amalitech.hospital.management.model.patient.Appointment;
import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity model for the `prescriptions` table.
 * Each prescription belongs to one appointment.
 */
@Data
@Entity
@Table(name = "prescriptions")
public class Prescription {

    /** PK — UUID generated by the database (gen_random_uuid()) */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "prescription_id", updatable = false, nullable = false)
    private String prescriptionId;

    /** FK -> appointments */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id", nullable = false,
            foreignKey = @ForeignKey(name = "fk_prescription_appointment"))
    private Appointment appointment;

    @Column(name = "date_issued", nullable = false)
    private LocalDate dateIssued;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;
}
